# Generated by Django 6.1 on 2026-08-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assignment_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='quiz_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='study_hours',
            field=models.FloatField(default=0),
        ),
    ]
