# Generated by Django 6.1 on 2026-08-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_student_father_name_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='performance_level',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='predicted_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
